# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 1
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/margo/Documents/Programming/VHDL/segmentDisplay/segmentDisplay.cache/wt [current_project]
set_property parent.project_path /home/margo/Documents/Programming/VHDL/segmentDisplay/segmentDisplay.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part_repo_paths {/home/margo/.Xilinx/Vivado/2019.1/xhub/board_store} [current_project]
set_property board_part digilentinc.com:cmod_a7-35t:part0:1.1 [current_project]
set_property ip_output_repo /home/margo/Documents/Programming/VHDL/segmentDisplay/segmentDisplay.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  /home/margo/Documents/Programming/VHDL/segmentDisplay/segmentDisplay.srcs/sources_1/new/timer.vhd
  /home/margo/Documents/Programming/VHDL/segmentDisplay/segmentDisplay.srcs/sources_1/new/segmentDisplay.vhd
  /home/margo/Documents/Programming/VHDL/segmentDisplay/segmentDisplay.srcs/sources_1/new/mux.vhd
  /home/margo/Documents/Programming/VHDL/segmentDisplay/segmentDisplay.srcs/sources_1/new/binary_bcd.vhd
  /home/margo/Documents/Programming/VHDL/segmentDisplay/segmentDisplay.srcs/sources_1/new/mux4_1.vhd
  /home/margo/Documents/Programming/VHDL/segmentDisplay/segmentDisplay.srcs/sources_1/new/uint16_seg_coder.vhd
  /home/margo/Documents/Programming/VHDL/segmentDisplay/segmentDisplay.srcs/sources_1/bd/design_main/hdl/design_main_wrapper.vhd
}
add_files /home/margo/Documents/Programming/VHDL/segmentDisplay/segmentDisplay.srcs/sources_1/bd/design_main/design_main.bd
set_property used_in_implementation false [get_files -all /home/margo/Documents/Programming/VHDL/segmentDisplay/segmentDisplay.srcs/sources_1/bd/design_main/design_main_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/margo/Documents/Programming/VHDL/segmentDisplay/segmentDisplay.srcs/constrs_1/new/constraints.xdc
set_property used_in_implementation false [get_files /home/margo/Documents/Programming/VHDL/segmentDisplay/segmentDisplay.srcs/constrs_1/new/constraints.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top design_main_wrapper -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef design_main_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file design_main_wrapper_utilization_synth.rpt -pb design_main_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
